apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: gateway-service
          livenessProbe:
            tcpSocket:
              port: 8080
              path: /alive
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 20
            failureThreshold: 10
            successThreshold: 1