apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: gateway-service
          readinessProbe:
            timeoutSeconds: 2
            periodSeconds: 15
            failureThreshold: 3
            httpGet:
              port: 8080
              path: /actuator/health
