apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: gateway-service
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: gateway-service
      jib: {}

profiles:
  - name: monkey
    activation:
      - kubeContext: dev/console-c3smonkey-ch:8443/developer
    build:
      insecureRegistries:
        - registry.apps.c3smonkey.ch
      tagPolicy:
        sha256: {}
      artifacts:
        - image: registry.apps.c3smonkey.ch/dev/gateway-service
          jib:
            args: ['-Dimage=registry.apps.c3smonkey.ch/dev/gateway-service']

    deploy:
      kubectl:
        manifests:
          - deployment.yaml

  - name: local
    build:
      tagPolicy:
        sha256: {}
      artifacts:
        - image: gateway-service
          jib: {}
      local:
        push: false

  - name: osp
    activation:
      - kubeContext: myhelsana-dev-az/osp-preprod-hel-kko-ch:443
    build:
      insecureRegistries:
        - registry.osp-appl-preprod.hel.kko.ch
      tagPolicy:
        sha256: {}
      artifacts:
        - image: registry.osp-appl-preprod.hel.kko.ch/myhelsana-dev-az/gateway-service
          jib:
            args: ['-Djib.from.image=registry.osp-appl-preprod.hel.kko.ch/myhelsana-build-dz/openjdk18-openshift:latest', '-Dimage=registry.osp-appl-preprod.hel.kko.ch/myhelsana-dev-az/gateway-service']

    deploy:
      kubectl:
        manifests:
          - deployment-osp.yaml


  - name: myhelsana-dev-ez
    activation:
      - kubeContext: myhelsana-dev-ez/osp-preprod-hel-kko-ch:443
    build:
      insecureRegistries:
        - registry.osp-appl-preprod.hel.kko.ch
      tagPolicy:
        sha256: {}
      artifacts:
        - image: registry.osp-appl-preprod.hel.kko.ch/myhelsana-dev-ez/gateway-service
          jib:
            args: ['-Djib.from.image=registry.osp-appl-preprod.hel.kko.ch/myhelsana-build-dz/openjdk18-openshift:latest', '-Dimage=registry.osp-appl-preprod.hel.kko.ch/myhelsana-dev-ez/gateway-service']

    deploy:
      kubectl:
        manifests:
          - deployment-myhelsana-dev-ez.yaml
