spring:
  profiles:
    active: default
    include: common

  cloud:
    gateway:
      routes:
        - id: catalog-service
          uri: http://localhost:8081
          predicates:
            - Path=/animal/**
          filters:
            - RewritePath=/animal/(?<path>.*), /$\{path}
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 2


---
spring:
  profiles: local

logging:
  level:
    root: debug

opentracing:
  jaeger:
    log-spans: true
    http-sender:
      url: http://localhost:14268/api/traces