---
spring:
  profiles: local
  cloud:
    gateway:
      routes:
        - id: whoami
          predicates:
            - Path=/whoami
          uri: forward:/whoami

logging:
  level:
    root: debug

opentracing:
  jaeger:
    log-spans: true
    http-sender:
      url: http://localhost:14268/api/traces
