spring:
  profiles:
    active: default
    include: common

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
          url-expression: "uri"
      # avoid sending forwarded/x-forwarded headers from api-gateway, as they overwrite forwarded headers from nevis or loadbalancer
      forwarded:
        enabled: false
      x-forwarded:
        enabled: true
        prefix-enabled: true # this header modifies the uri of the request within the called service
        prefix-append: false
        proto-enabled: false
        proto-append: false
        port-enabled: false
        port-append: false
        host-enabled: false
        host-append: false
        for-enabled: false
        for-append: false

      routes:
        - id: catalog-service
          uri: http://localhost:8081
          predicates:
            - Path=/animal/**
          filters:
            - RewritePath=/animal/(?<path>.*), /$\{path}
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 2


