
app:
  root:
    context: /coolapp*
    service: ${app.root.context}/services

spring:
  profiles:
    active: default
    include: common
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          url-expression: "uri"