app:
  root:
    context: /myhelsana2*
    service: ${app.root.context}/services

spring:

  redis:
    host: redis.myhelsana-dev-ez.svc.cluster.local
    port: 6379
    jedis:
      pool:
        maxIdle: 50 # max idle connections in the pool
        minIdle: 10 # min idle connections in the pool
        maxActive: -1 # no limit to the number of active connections
        maxWait: 30000 # time limit to get a connection - only applies if maxActive is finite
    password: ${REDIS_PASSWORD}

  cloud:
    gateway:
      routes:
        - id: webforms-service
          predicates:
            - Path=${app.root.context}/**
          uri: http://webforms-service:8080
          filters:
            - StripPrefix=1

opentracing:
  jaeger:
    log-spans: true
    http-sender:
      url: http://jaeger-collector.helsana-appmon-az.svc.cluster.local:14268/api/traces
