---
spring:
  config:
    activate:
      on-profile: local

  cloud:
    gateway:
      routes:
        - id: whoami
          predicates:
            - Path=/whoami
          uri: forward:/whoami

logging:
  level:
    root: debug
