apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: myhelsana-dev-ez

commonLabels:
  env: dev
  app: gateway-service

commonAnnotations:
  component: fsl-backend

images:
  - name: docker-registry.default.svc:5000/myproject/demo
    newName: docker-registry.default.svc:5000/myhelsana-dev-ez/gateway-service
    newTag: latest

resources:
  - ../../base/
  - route.yaml

patchesStrategicMerge:
  - patch-memorylimit.yaml
  - update-replicas.yaml
  - use-configmap.yaml
  - use-secrets.yaml

configMapGenerator:
  - name: gateway-service-config
    files:
      - ./config-files/bootstrap.yaml
      - ./config-files/application.yaml

secretGenerator:
  - name: gateway-service-secret
    literals:
      - spring.redis.password={cipher}c9a200abe5fcb1f86f89dbd2da3360943c1cf8c2c6be28ef3afe952ba5cd7bfd2c5f5c142de20d9f951a7c60fcda7be2

