# curl http://localhost:8080/api/foo -H "Authorization: Bearer  $token" -v
# http :8080/light  "Authorization: Bearer $token"
GET http://localhost:8080/api/foo
Accept: */*
Cache-Control: no-cache
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJkZjhmZTRhOC02NjM2LTQ1ZmQtODE3Zi0xYWI2MzY4NzY3MDgiLCJzdWIiOiJBMTAwMjU5MyIsImlhdCI6MTU4NDIwNTk2MCwiZXhwIjoxNTg0MjA5NTYwMiwiaXNzIjoiS2VlcGNhbG0gQXV0aCBQb3J0YWwiLCJhdWQiOiJLZWVwY2FsbSIsImxhbmd1YWdlIjoiZGUiLCJuYW1lIjoiS2VlcGNhbG0gQUciLCJmaXJzdE5hbWUiOiJKb2huIiwiaXNlbXBsb3llZSI6ZmFsc2UsImVtYWlsIjoia2VlcGNhbG1AYzNzbW9ua2V5LmNoIiwicm9sZXMiOiJrZWVwY2FsbS51c2VyIiwicGFydG5lcmlkIjoiNjAwMTE0ODQiLCJwYXJ0bmVybnIiOiJNNjAwMTE0ODQiLCJhbGxvd2Vka2V5cyI6IjYwMDExNDg0In0.obrwFFNZHvS9U41_nPhqOyr25kB_iyJmWd9mI478WDA
###


# curl http://localhost:8080/light -H "Authorization: Bearer  $tokenLight" -v
# http :8080/light  "Authorization: Bearer $tokenLight"
GET http://localhost:8080/light
Accept: */*
Cache-Control: no-cache
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIwYTcwMmU3OS1hOWMwLTQxYjktOGRiOC1kOTA1YjUyNTJjYmUiLCJzdWIiOiJBMTAwMjU5MyIsImlhdCI6MTU4NDIwNjE0MSwiZXhwIjoxNTg0MjA5NzQxMywiaXNzIjoiS2VlcGNhbG0gQXV0aCBQb3J0YWwiLCJhdWQiOiJLZWVwY2FsbSIsImxhbmd1YWdlIjoiZGUiLCJuYW1lIjoiS2VlcGNhbG0gQUciLCJmaXJzdE5hbWUiOiJKb2huIiwiaXNlbXBsb3llZSI6ZmFsc2UsImVtYWlsIjoia2VlcGNhbG1AYzNzbW9ua2V5LmNoIiwicm9sZXMiOiJrZWVwY2FsbS5saWdodCIsInBhcnRuZXJpZCI6IjYwMDExNDg0IiwicGFydG5lcm5yIjoiTTYwMDExNDg0IiwiYWxsb3dlZGtleXMiOiI2MDAxMTQ4NCJ9.DU_HV7RaQGxT52qXalTvhN1gxzaEoVjBciSTVWb9HJA
###


### Get gateway
GET http://gateway-service-dev.apps.c3smonkey.ch/myhls/services/customers
Accept: */*
Cache-Control: no-cache
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJIZWxzYW5hIEF1dGggUG9ydGFsIiwic3ViIjoibm91c2VyIiwicm9sZXMiOiJteWhlbHNhbmEubGlnaHQiLCJpYWQiOjE1NzI2Mjg5NDAsImV4cCI6MTYwNDE4NjU0MCwiYXVkIjoiSGVsc2FuYSIsImxhbmd1YWdlIjoiZGUiLCJwYXJ0bmVyaWQiOiJub3VzZXIiLCJwYXJ0bmVybnIiOiIxMjM0NTY3OCJ9.aY2R174A427Q6Gi9gQz6AoluHzfbK2cafIuoXFAE4sY
Forwarded: for="portal.azure.com";host="portal.azure.com";proto="https";
X-Forwarded-Host: hallo
X-Forwarded-Proto: https
###


