apiVersion: apps/v1
kind: Deployment
metadata:    
  name: gateway-service
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: gateway-service
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 500m
              memory: 500Mi
          env:
            - name: MEM_TOTAL_MB
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory

