apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

commonLabels:
  env: dev

commonAnnotations:
  component: fsl-backend

images:
  - name: docker-registry.default.svc:5000/myproject/demo
    newName: docker-registry.default.svc:5000/dev/gateway-service
    newTag: latest

resources:
  - ../../base/
  - route.yaml

patchesStrategicMerge:
  - patch-memorylimit.yaml
  - update-replicas.yaml
  - use-configmap.yaml
  - use-secrets.yaml

configMapGenerator:
  - name: gateway-service-config
    files:
      - ./config-files/application.yaml

secretGenerator:
  - name: gateway-service-secret
    literals:
      - REDIS_PASSWORD=yQbT0Iy35nlADTL3

