apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  template:
    spec:
      containers:
        - name: gateway-service
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gateway-service-secret
                  key: REDIS_PASSWORD

